apiVersion: apps/v1
kind: Deployment
metadata:
  name: dd-garbage-routes-controller
  namespace: dd-garbage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dd-garbage-routes-controller
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /metrics
        prometheus.io/port: '443'
      labels:
        app: dd-garbage-routes-controller
    spec:
      containers:
      - name: dd-garbage-routes-controller
        image: dd-garbage-routes-controller:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 250m
---
apiVersion: v1
kind: Service
metadata:
  name: dd-garbage-routes-controller-entrypoint
  namespace: dd-garbage
spec:
  type: NodePort
  selector:
    app: dd-garbage-routes-controller
  ports:
  - port: 443
    targetPort: 443
    nodePort: 30003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dd-garbage-routes-dh
  namespace: dd-garbage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dd-garbage-routes-dh
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /metrics
        prometheus.io/port: '443'
      labels:
        app: dd-garbage-routes-dh
    spec:
      containers:
      - name: dd-garbage-routes-dh
        image: dd-garbage-routes-dh:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 250m
---
apiVersion: v1
kind: Service
metadata:
  name: dd-garbage-routes-dh-entrypoint
  namespace: dd-garbage
spec:
  selector:
    app: dd-garbage-routes-dh
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dd-garbage-routes-eh
  namespace: dd-garbage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dd-garbage-routes-eh
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /metrics
        prometheus.io/port: '443'
      labels:
        app: dd-garbage-routes-eh
    spec:
      containers:
      - name: dd-garbage-routes-eh
        image: dd-garbage-routes-eh:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 250m
---
apiVersion: v1
kind: Service
metadata:
  name: dd-garbage-routes-eh-entrypoint
  namespace: dd-garbage
spec:
  selector:
    app: dd-garbage-routes-eh
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dd-garbage-routes-reflection
  namespace: dd-garbage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dd-garbage-routes-reflection
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /metrics
        prometheus.io/port: '443'
      labels:
        app: dd-garbage-routes-reflection
    spec:
      containers:
      - name: dd-garbage-routes-reflection
        image: dd-garbage-routes-reflection:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dd-garbage-routes-virtualizer
  namespace: dd-garbage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dd-garbage-routes-virtualizer
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /metrics
        prometheus.io/port: '443'
      labels:
        app: dd-garbage-routes-virtualizer
    spec:
      containers:
      - name: dd-garbage-routes-virtualizer
        image: dd-garbage-routes-virtualizer:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 250m
---
apiVersion: v1
kind: Service
metadata:
  name: dd-garbage-routes-virtualizer-entrypoint
  namespace: dd-garbage
spec:
  selector:
    app: dd-garbage-routes-virtualizer
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
  type: ClusterIP
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: dd-garbage-routes-controller
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dd-garbage-routes-controller
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: dd-garbage-routes-dh
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dd-garbage-routes-dh
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50